#cloud-config

yum_repos:
    # The name of the repository
    epel:
        baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
        enabled: true
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
        name: Extra Packages for Enterprise Linux 7 - $basearch

    epel-debuginfo:
        baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch/debug
        enabled: false
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
        name: Extra Packages for Enterprise Linux 7 - $basearch - Debug

    epel-source:
        baseurl: https://mirrors.fedoraproject.org/metalink?repo=epel-source-7&arch=$basearch
        enabled: false
        failovermethod: priority
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
        name: Extra Packages for Enterprise Linux 7 - $basearch - Source
