#cloud-config
users:
  - name: @@{LinuxAdmin.username}@@
    ssh-authorized-keys:
      - @@{LinuxAdmin_PUBLIC_KEY}@@
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_pwauth: True
    password: "@@{LinuxUser.secret}@@"
    chpasswd: { expire: False }
    shell: /bin/bash
# Set hostname
hostname: "@@{HOST_NAME}@@"
Set timezone
timezone: US/Central
# Install packages
packages:
  - git
  - wget
  - curl
  - unzip
  - tar
  - python3
  - cloud-guest-utils
growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false  
package_update: true
package_upgrade: true
final_message: "The system is finally up, after $UPTIME seconds"