#cloud-config

# Add Connection Inc. yum repository configuration to the system

yum_repos:
    epel_rhel7_x86_64:
        baseurl: 
        enabled: true
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-X
        name: XXX
#
    rhel-x86_64-server-extras-7:
        baseurl: 
        enabled: true
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-X
        name: XXX
#
rhel-x86_64-server-optional-7:
        baseurl: 
        enabled: true
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-X
        name: XXX
#
rhel-x86_64-server-7-rhscl-1:
        baseurl: 
        enabled: true
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-X
        name: XXX
#
rhn-tools-rhel-x86_64-server-7:
        baseurl: 
        enabled: true
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-X
        name: XXX