#cloud-config

# Create User with SSH Credentials
users:
  - name: akbar
    ssh-authorized-keys:
    - ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDj+AlcFfYz196KK5IgVLeILvWSTssrQTWnxJrG3ljIJ55RSuuVsWGUigj59EuS8SF4c8l+q/XtXbdqjbmBPywRuVbbsMl3uCtMtU1NxYJne3UnAn7Z7SccZq65XHaSYkmV+0k9CiJQJ6Y+HAT09MUl42l8KkO8xs6IvrIgdDriv++s2eyfSBj6/UJgm0axf8VfC159AoaKpHm9xXGNQUr3LNKQNWTpsCBfJyFiHq/mjFzOUEiKi6a8Rqs/Wy9NzhaKjyC+4XAs47v8DfG8GB7S/093TMnEBfWxuU06n0a7AEBeppErgwMM/ks40igM6rWPC4D48jkZt9p+Q0i7sgT akbar@PC0JUQTE
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

# Modify SSH Configuration to allow specific parameters
write_files:
  - path: /etc/ssh/sshd_config
    content: |
          Port 22
          Protocol 2
          HostKey /etc/ssh/ssh_host_rsa_key
          HostKey /etc/ssh/ssh_host_dsa_key
          HostKey /etc/ssh/ssh_host_ecdsa_key
          UsePrivilegeSeparation yes
          KeyRegenerationInterval 3600
          ServerKeyBits 1024
          SyslogFacility AUTH
          LogLevel INFO
          LoginGraceTime 120
          PermitRootLogin no
          StrictModes yes
          RSAAuthentication yes
          PubkeyAuthentication yes
          IgnoreRhosts yes
          RhostsRSAAuthentication no
          HostbasedAuthentication no
          PermitEmptyPasswords no
          ChallengeResponseAuthentication no
          X11Forwarding yes
          X11DisplayOffset 10
          PrintMotd no
          PrintLastLog yes
          TCPKeepAlive yes
          AcceptEnv LANG LC_*
          Subsystem sftp /usr/lib/openssh/sftp-server
          UsePAM yes
          AllowUsers akbar

# Restart is required after the above changes are made to take effect. 
runcmd:
  - restart ssh